//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rajpal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminClient
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string EmailId { get; set; }
        public string DOB { get; set; }
        public string PhoneNo { get; set; }
        public string Source { get; set; }
        public string Status { get; set; }
        public string Gender { get; set; }
        public string Photopath { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsEmailSend { get; set; }
    }
}
