//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rajpal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsLetter
    {
        public int NewsLetterId { get; set; }
        public string NewsLetterName { get; set; }
        public string Image { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<System.DateTime> fwd_date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string second_Image { get; set; }
    }
}
