//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rajpal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DreamHouseImages
    {
        public int Id { get; set; }
        public Nullable<int> DreamHouseId { get; set; }
        public string ImageUrl { get; set; }
    }
}
