//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rajpal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SiteSettings
    {
        public int SiteID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public string Copyright { get; set; }
        public byte[] UploadLogo { get; set; }
        public byte[] Favicon_ico { get; set; }
        public string SiteTemplate { get; set; }
        public string BannerSettings { get; set; }
        public string PhoneNumber { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public byte[] BannerImage { get; set; }
        public string Fax { get; set; }
        public byte[] ContactImage { get; set; }
        public string ListBrokerage { get; set; }
    }
}
