//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rajpal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PageBlogs
    {
        public int ID { get; set; }
        public string PageName { get; set; }
        public string PageTitle { get; set; }
        public string PageDescription { get; set; }
        public string PageType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IncludeInMenu { get; set; }
        public Nullable<bool> IncludeInSubMenu { get; set; }
        public Nullable<int> SubMenuPageID { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
        public string SubMenuPageName { get; set; }
        public string PageLocation { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Metatag { get; set; }
        public string MetaDiscription { get; set; }
    }
}
